### PR TITLE
Expand podcasts section

### PR DESCRIPTION
**Pull request by chillenzer**
After the discussion in the rocket.chat, here are the remaining contributions in terms of podcasts. Two points I want to raise in advance:
- The podcasts as well as some of the already merged podcasts are not very RSE-specific. Surely educational, but not precisely tailored. Also, there are quite a few `awesome-{programming-,}podcasts{-tech,}` lists one could refer to instead. But none of those really got quite what I was looking for, so I still created this PR. If you feel differently about this, having a closer look at those lists and referring to one of them would be an option.
- [Developer stories](https://rseng.github.io/devstories/) should definitely be in here but as I personally haven't listened to it (yet), so I can't -- in the spirit of an awesome list -- really make that recommendation. But if someone has listened to it (or wants to do it for this PR), we should very likely add it.

### CODE REVIEW

**Comment by geyslein** [comment]
Hey @chillenzer , thanks for pointing this out. I share your doubts. I'd avoid redundancy and would keep the focus on RSE. So I'd suggest to collect here (more or less) pure RSE podcasts and skip all the others (even more if there are other lists existing)

**Comment by geyslein** [comment]
hey @chillenzer , I close this one, right?

**Comment by chillenzer** [comment]
No, if you want to go this route, then we should actually get rid of the other non-RSE podcasts here, too. Updated the PR and included Developer Stories and Code For Thought now as the only really focused ones.

**Review by geyslein — APPROVED** [review]
Thank you, I'd go for RSE podcasts only.

**Comment by geyslein** [comment]
hey @chillenzer thank you for your contribution. you were talking about `awesome-{programming-,}podcasts{-tech,}`. we could shortly reference these awesome lists as well.

**Comment by chillenzer** [comment]
I had another look at that and I don't think there is much of a value in that. There are loads of them, so listing them all is not an option, and personally I don't have experience with which are any good. Also, they are pretty straightforward to find. The most we could do would be something like adding a sentence before and after it. Maybe:
```
To the best of our knowledge, there are two RSE-specific podcasts out there:
[list here]
Of course, there are many more technical podcasts that could be of interest. Please see the more pertinent Awesome Lists for that.
```

**Pull request merged**
